### ISSUE TITLE
^H documentation for selection fails

### ISSUE THREAD

**Issue by raldred** [kswedberg/jquery-tmbundle#12]
```
/Users/robaldred/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/rexml/parsers/treeparser.rb:92:in `parse': #<rexml::parseexception: no="" close="" tag="" for="" api=""> (REXML::ParseException)
/Users/robaldred/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/rexml/parsers/treeparser.rb:28:in `parse'
/Users/robaldred/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/rexml/document.rb:227:in `build'
/Users/robaldred/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/rexml/document.rb:43:in `initialize'
/tmp/temp_textmate.2w7pZv:8:in `new'
/tmp/temp_textmate.2w7pZv:8
...
No close tag for /api
Line: 17243
Position: 818162
Last 80 unconsumed characters:
    from /Users/robaldred/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/rexml/document.rb:227:in `build'
    from /Users/robaldred/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/rexml/document.rb:43:in `initialize'
    from /tmp/temp_textmate.2w7pZv:8:in `new'
    from /tmp/temp_textmate.2w7pZv:8
</rexml::parseexception:>
```

**Comment by kswedberg** [comment]
Ack! thanks so much for pointing this out. I'll get on it asap!

**Comment by raldred** [comment]
Cool, I guess somethings changed in the api of wherever you're getting the docs from?
If I can help any further let me know.

Rob

**Comment by kswedberg** [comment]
Looks like it was just a copy/paste error on my part (had <?xml version="1.0" ?><api> in there twice.)

Thanks again for the report!

**Comment by raldred** [comment]
Superb turnaround. Thanks!
